stages:
  - build

run-build:
  except:
    - develop
  image: amd64/debian:buster
  before_script:
    - apt-get update -qq && apt-get install
  stage: build
  script:
    - apt-get install -y python3-dev libgnucap-dev gnucap-default-plugins0 python3-scipy python3-numpy gnucap build-essential autotools-dev g++ swig libtool autoconf automake
    - ./bootstrap
    - ./configure PYTHON=python3
    - make distcheck PYTHON=python3 || \
      cat gnucap-python-0.0.3-wip/_build/sub/tests/*.log
